# Generated by Django 5.1.1 on 2024-11-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_52_3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
